#!/usr/bin/env bash
# Configure only a lab rootfs explicitly marked by build-debian.sh.
set -euo pipefail
fail() { echo "ERROR: $*" >&2; exit 2; }
[[ ${1:-} != --help && ${1:-} != -h ]] || { echo 'Usage: configure-rootfs.sh ROOTFS SSH_PUBLIC_KEY [--dry-run]'; exit 0; }
(($# >= 2 && $# <= 3)) || fail 'rootfs and public key required'
target=$(realpath -e -- "$1")
key=$(realpath -e -- "$2")
[[ -z ${3:-} || ${3:-} == --dry-run ]] || fail 'unknown option'
[[ "$target" != / && "$target" != /mnt/* ]] || fail 'unsafe rootfs target'
if [[ ! -f "$target/.q11-lab-build" ]] || ! grep -qx Q11_DEBIAN_ARMHF_LAB_V1 "$target/.q11-lab-build"; then fail 'rootfs lacks the lab build marker'; fi
[[ -f "$target/etc/debian_version" ]] || fail 'missing Debian rootfs'
[[ -f "$key" ]] || fail 'missing public key'
[[ $(wc -c <"$key") -le 16384 && $(grep -c . "$key") == 1 ]] || fail 'provide one public key (max 16 KiB)'
grep -Eq '^(ssh-|ecdsa-|sk-)[^ ]+ [A-Za-z0-9+/]+=*([[:space:]].*)?$' "$key" || fail 'public key text required; private keys are rejected'
ssh-keygen -lf "$key" >/dev/null || fail 'invalid public key'
[[ ${3:-} != --dry-run ]] || { echo 'DRY RUN: marked lab rootfs configuration'; exit 0; }
[[ $EUID == 0 ]] || fail 'run as root'
install -m 0755 "$(command -v qemu-arm-static)" "$target/usr/bin/qemu-arm-static"
run_target() {
    # WSL distributions share binfmt handlers; another startup can reset them.
    if [[ $(uname -m) != armv7l && ! -f /proc/sys/fs/binfmt_misc/qemu-arm ]]; then
        [[ -f /usr/lib/binfmt.d/qemu-arm.conf ]] || fail 'missing installed qemu-arm binfmt config'
        cat /usr/lib/binfmt.d/qemu-arm.conf >/proc/sys/fs/binfmt_misc/register
    fi
    # Execute shebang scripts through a target shell; qemu itself expects ELF.
    timeout 600 chroot "$target" /usr/bin/qemu-arm-static /bin/sh -c 'exec "$@"' q11-target "$@" || fail "target command failed: $1"
}
[[ $(run_target /usr/bin/dpkg --print-architecture) == armhf ]] || fail 'rootfs must be armhf'
cat >"$target/etc/apt/sources.list" <<'EOF'
deb https://deb.debian.org/debian bookworm main
deb https://deb.debian.org/debian bookworm-updates main
deb https://security.debian.org/debian-security bookworm-security main
EOF
echo q11 >"$target/etc/hostname"
printf '127.0.0.1 localhost\n127.0.1.1 q11\n::1 localhost ip6-localhost\n' >"$target/etc/hosts"
mkdir -p "$target/etc/network/interfaces.d" "$target/etc/ssh/sshd_config.d"
cat >"$target/etc/network/interfaces" <<'EOF'
auto lo
iface lo inet loopback
allow-hotplug eth0
iface eth0 inet dhcp
EOF
cat >"$target/etc/ssh/sshd_config.d/q11.conf" <<'EOF'
PermitRootLogin no
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
UsePAM yes
EOF
if ! grep -q "^developer:" "$target/etc/passwd"; then run_target /usr/sbin/useradd -m -s /bin/bash developer; fi
mkdir -p "$target/home/developer/.ssh"
install -m 0600 "$key" "$target/home/developer/.ssh/authorized_keys"
run_target /bin/chown -R developer:developer /home/developer/.ssh
chmod 0700 "$target/home/developer/.ssh"
# Root has no network password; serial console is the local administrative access.
run_target /usr/sbin/usermod -p '*' root
sed -i '/^T0:/d' "$target/etc/inittab"
echo 'T0:2345:respawn:/sbin/agetty --autologin root --noclear -L ttyAMA0 115200 vt100' >>"$target/etc/inittab"
cat >"$target/etc/fstab" <<'EOF'
# Root is mounted by initramfs; external root only. No internal MTD mounts.
/dev/root / ext4 defaults,noatime 0 1
proc /proc proc defaults 0 0
sysfs /sys sysfs defaults 0 0
devpts /dev/pts devpts gid=5,mode=620 0 0
tmpfs /run tmpfs mode=0755,nosuid,nodev 0 0
EOF
cat >"$target/etc/init.d/q11-firstboot" <<'EOF'
#!/bin/sh
### BEGIN INIT INFO
# Provides: q11-firstboot
# Required-Start: $local_fs
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:
# X-Start-Before: ssh
# Short-Description: Generate per-install SSH host keys
### END INIT INFO
set -eu
case "${1:-}" in start) ssh-keygen -A ;; stop|status|restart|force-reload) : ;; *) exit 2 ;; esac
EOF
chmod 0755 "$target/etc/init.d/q11-firstboot"
run_target /usr/sbin/update-rc.d q11-firstboot defaults
# Only remove keys generated by this fresh image's package installation.
find "$target/etc/ssh" -maxdepth 1 -type f -name 'ssh_host_*' -delete

# Verify with explicit emulator before removing the host build helper.
run_target /bin/sh -c 'test -x /sbin/init && test -x /usr/sbin/sshd && /bin/busybox --list | grep -qx switch_root'
run_target /bin/busybox --list >"$target.busybox-applets.txt"
run_target /usr/bin/dpkg-query -W >"$target.packages.tsv"
sha256sum "$target/bin/busybox" >"$target.busybox.sha256"
echo 'result=host-built; Q11 kernel/userspace compatibility and image loading remain untested'

rm -f -- "$target/usr/sbin/policy-rc.d" "$target/usr/bin/qemu-arm-static"
